Mysql database change to use google sql instance (#18)
* mysql database change

* updated shell scripts

* packer fmt issue resolved

* updated actions jobs

* updated actions

* rearranged actions

diff --git a/.github/workflows/packer.yml b/.github/workflows/packer.yml
--- a/.github/workflows/packer.yml
+++ b/.github/workflows/packer.yml
@@ -38,12 +38,19 @@ jobs:
           zip -r webapp.zip .
           mv webapp.zip packer/shell/
 
+      - name: Run packer fmt
+        run: |
+          cd packer/
+          if ! packer fmt -check . ; then
+            echo "Failed - Packer fmt"
+            exit 1
+          fi
+
       - name: Create variables file from secrets
         run: |
           cat <<EOF > packer/variables.pkrvars.hcl
           vpc_name                       = "default"
           project_id                     = "${{ secrets.GCP_DEV_PROJECT_ID }}"
-          var_count                      = 1
           app_name                       = "webapp"
           ssh_username                   = "centos"
 
@@ -53,23 +60,16 @@ jobs:
         run: |
           cd packer/
           if ! packer init . ; then
-          echo "Failed - Packer init"
-          exit 1
-          fi
-
-      - name: Run packer fmt
-        run: |
-            if ! packer fmt -check . ; then
-            echo "Failed - Packer fmt"
+            echo "Failed - Packer init"
             exit 1
-            fi
-
+          fi
+          
       - name: Validate Packer configuration
         run: |
           cd packer/
           if ! packer validate -var-file="variables.pkrvars.hcl" . ; then
-          echo "Failed - Packer validate"
-          exit 1
+            echo "Failed - Packer validate"
+            exit 1
           fi
 
       - name: Run Packer build
@@ -78,6 +78,6 @@ jobs:
           packer init .
           packer plugins install github.com/hashicorp/googlecompute
           if ! packer build -var-file="variables.pkrvars.hcl" . ; then
-          echo "Failed - Packer build"
-          exit 1
+            echo "Failed - Packer build"
+            exit 1
           fi
